<?php

/**
 * Isolated UI mock data for Stage 1 order architecture screens.
 * Not loaded by production order services, controllers, or catalog lookups.
 *
 * Returned array is extract()'d into the calling Blade view so variables stay in parent scope.
 * Blade @include cannot leak @php locals back to the parent.
 *
 * Expects $orderUiScreen (optional) already in scope from ui-urls-data.php extract.
 */

$orderUiMockOrders = [
    [
        'id' => 9001,
        'orderNumber' => 'FO-24001',
        'customerName' => 'Sanduni Wijesinghe',
        'customerPhone' => '0771234567',
        'secondaryPhone' => '0112345678',
        'address' => 'No. 12, Temple Road, Negombo',
        'itemCount' => 2,
        'itemCode' => '1842',
        'itemName' => 'Vitamin C Serum / 30ml',
        'amount' => 4850,
        'subtotal' => 4500,
        'discount' => 150,
        'courierFee' => 500,
        'currency' => 'LKR',
        'assignment' => 'unassigned',
        'ccaId' => null,
        'ccaName' => null,
        'supplierId' => 'supplier-1',
        'supplierName' => 'Lanka Beauty Supply',
        'status' => 'pending',
        'statusLabel' => 'Pending',
        'source' => 'manual',
        'createdAt' => '2026-09-13T08:15:00+05:30',
        'courierName' => null,
        'district' => 'Gampaha',
        'city' => 'Negombo',
        'workspace' => 'call-center',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9002,
        'orderNumber' => 'FO-24002',
        'customerName' => 'Ruwan Silva',
        'customerPhone' => '0769876543',
        'secondaryPhone' => '',
        'address' => '45 Galle Road, Dehiwala',
        'itemCount' => 1,
        'itemCode' => '1901',
        'itemName' => 'Hair Oil / 100ml',
        'amount' => 3200,
        'subtotal' => 2800,
        'discount' => 0,
        'courierFee' => 400,
        'currency' => 'LKR',
        'assignment' => 'assigned',
        'ccaId' => 'cca-1',
        'ccaName' => 'Nimali Perera',
        'supplierId' => 'supplier-2',
        'supplierName' => 'Island Wellness',
        'status' => '1st-attempt',
        'statusLabel' => '1st Attempt',
        'source' => 'meta',
        'createdAt' => '2026-09-13T09:40:00+05:30',
        'courierName' => null,
        'district' => 'Colombo',
        'city' => 'Dehiwala',
        'workspace' => 'call-center',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9003,
        'orderNumber' => 'FO-24003',
        'customerName' => 'Ayesha Fernando',
        'customerPhone' => '0751122334',
        'secondaryPhone' => '0770001122',
        'address' => '88 Peradeniya Road, Kandy',
        'itemCount' => 3,
        'itemCode' => '1760',
        'itemName' => 'Collagen Cream / 50ml',
        'amount' => 8900,
        'subtotal' => 8600,
        'discount' => 300,
        'courierFee' => 600,
        'currency' => 'LKR',
        'assignment' => 'pool',
        'ccaId' => null,
        'ccaName' => null,
        'supplierId' => 'supplier-1',
        'supplierName' => 'Lanka Beauty Supply',
        'status' => '2nd-attempt',
        'statusLabel' => '2nd Attempt',
        'source' => 'manual',
        'createdAt' => '2026-09-12T16:05:00+05:30',
        'courierName' => null,
        'district' => 'Kandy',
        'city' => 'Kandy',
        'workspace' => 'call-center',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9004,
        'orderNumber' => 'FO-24004',
        'customerName' => 'Tharindu Jayasuriya',
        'customerPhone' => '0715566778',
        'secondaryPhone' => '',
        'address' => '7 Hill Street, Gampaha',
        'itemCount' => 1,
        'itemCode' => '2014',
        'itemName' => 'Face Wash / 150ml',
        'amount' => 2100,
        'subtotal' => 1750,
        'discount' => 0,
        'courierFee' => 350,
        'currency' => 'LKR',
        'assignment' => 'assigned',
        'ccaId' => 'cca-2',
        'ccaName' => 'Kasun Jayawardena',
        'supplierId' => 'supplier-2',
        'supplierName' => 'Island Wellness',
        'status' => '3rd-attempt',
        'statusLabel' => '3rd Attempt',
        'source' => 'manual',
        'createdAt' => '2026-09-12T11:22:00+05:30',
        'courierName' => null,
        'district' => 'Gampaha',
        'city' => 'Gampaha',
        'workspace' => 'call-center',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9005,
        'orderNumber' => 'FO-24005',
        'customerName' => 'Malsha Perera',
        'customerPhone' => '0773344556',
        'secondaryPhone' => '0114455667',
        'address' => '21 Marine Drive, Colombo',
        'itemCount' => 2,
        'itemCode' => '1842',
        'itemName' => 'Vitamin C Serum / 30ml',
        'amount' => 5400,
        'subtotal' => 5000,
        'discount' => 200,
        'courierFee' => 600,
        'currency' => 'LKR',
        'assignment' => 'assigned',
        'ccaId' => 'cca-3',
        'ccaName' => 'Ishara Fernando',
        'supplierId' => 'supplier-1',
        'supplierName' => 'Lanka Beauty Supply',
        'status' => 'hold',
        'statusLabel' => 'Hold',
        'source' => 'manual',
        'createdAt' => '2026-09-11T14:10:00+05:30',
        'courierName' => 'Pronto Lanka',
        'district' => 'Colombo',
        'city' => 'Colombo',
        'workspace' => 'call-center',
        'holdReminder' => '2026-09-16',
        'holdNote' => 'Customer asked to call after 6pm on Tuesday.',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9006,
        'orderNumber' => 'FO-24006',
        'customerName' => 'Janith Bandara',
        'customerPhone' => '0707788990',
        'secondaryPhone' => '',
        'address' => '9 Station Road, Ja-Ela',
        'itemCount' => 1,
        'itemCode' => '1888',
        'itemName' => 'Sunscreen / 50ml',
        'amount' => 3600,
        'subtotal' => 3200,
        'discount' => 0,
        'courierFee' => 400,
        'currency' => 'LKR',
        'assignment' => 'assigned',
        'ccaId' => 'cca-1',
        'ccaName' => 'Nimali Perera',
        'supplierId' => 'supplier-2',
        'supplierName' => 'Island Wellness',
        'status' => 'confirmed',
        'statusLabel' => 'Confirmed',
        'source' => 'manual',
        'createdAt' => '2026-09-10T10:05:00+05:30',
        'courierName' => 'Island Express',
        'district' => 'Gampaha',
        'city' => 'Ja-Ela',
        'workspace' => 'archived',
        'archive' => 'completed',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9007,
        'orderNumber' => 'FO-24007',
        'customerName' => 'Dilani Gunasekara',
        'customerPhone' => '0756677889',
        'secondaryPhone' => '0771112233',
        'address' => '3 Lake View, Nugegoda',
        'itemCount' => 1,
        'itemCode' => '1760',
        'itemName' => 'Collagen Cream / 50ml',
        'amount' => 4100,
        'subtotal' => 3800,
        'discount' => 100,
        'courierFee' => 400,
        'currency' => 'LKR',
        'assignment' => 'unassigned',
        'ccaId' => null,
        'ccaName' => null,
        'supplierId' => 'supplier-1',
        'supplierName' => 'Lanka Beauty Supply',
        'status' => 'cancelled',
        'statusLabel' => 'Cancelled',
        'source' => 'meta',
        'createdAt' => '2026-09-09T18:40:00+05:30',
        'courierName' => null,
        'district' => 'Colombo',
        'city' => 'Nugegoda',
        'workspace' => 'call-center',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9008,
        'orderNumber' => 'FO-24008',
        'customerName' => 'Hasitha Weerasinghe',
        'customerPhone' => '0724455667',
        'secondaryPhone' => '',
        'address' => '16 Kandy Road, Maharagama',
        'itemCount' => 2,
        'itemCode' => '1901',
        'itemName' => 'Hair Oil / 100ml',
        'amount' => 2750,
        'subtotal' => 2400,
        'discount' => 0,
        'courierFee' => 350,
        'currency' => 'LKR',
        'assignment' => 'pool',
        'ccaId' => null,
        'ccaName' => null,
        'supplierId' => 'supplier-2',
        'supplierName' => 'Island Wellness',
        'status' => 'expiring',
        'statusLabel' => 'Expiring',
        'source' => 'manual',
        'createdAt' => '2026-09-06T09:00:00+05:30',
        'courierName' => null,
        'district' => 'Colombo',
        'city' => 'Maharagama',
        'workspace' => 'call-center',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9011,
        'orderNumber' => 'FO-24011',
        'customerName' => 'Kavindu Perera',
        'customerPhone' => '0778899001',
        'secondaryPhone' => '',
        'address' => '40 Beach Road, Mount Lavinia',
        'itemCount' => 1,
        'itemCode' => '1888',
        'itemName' => 'Sunscreen / 50ml',
        'amount' => 2950,
        'subtotal' => 2550,
        'discount' => 0,
        'courierFee' => 400,
        'currency' => 'LKR',
        'assignment' => 'unassigned',
        'ccaId' => null,
        'ccaName' => null,
        'supplierId' => 'supplier-3',
        'supplierName' => 'Ceylon Care Depot',
        'status' => 'pending',
        'statusLabel' => 'Pending',
        'source' => 'manual',
        'createdAt' => '2026-09-13T07:05:00+05:30',
        'courierName' => null,
        'district' => 'Colombo',
        'city' => 'Mount Lavinia',
        'workspace' => 'call-center',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9012,
        'orderNumber' => 'FO-24012',
        'customerName' => 'Sachini Madushani',
        'customerPhone' => '0752233445',
        'secondaryPhone' => '0116677889',
        'address' => '18 High Level Road, Maharagama',
        'itemCount' => 2,
        'itemCode' => '2014',
        'itemName' => 'Face Wash / 150ml',
        'amount' => 4300,
        'subtotal' => 3900,
        'discount' => 100,
        'courierFee' => 500,
        'currency' => 'LKR',
        'assignment' => 'assigned',
        'ccaId' => 'cca-2',
        'ccaName' => 'Kasun Jayawardena',
        'supplierId' => 'supplier-1',
        'supplierName' => 'Lanka Beauty Supply',
        'status' => '1st-attempt',
        'statusLabel' => '1st Attempt',
        'source' => 'manual',
        'createdAt' => '2026-09-12T19:20:00+05:30',
        'courierName' => null,
        'district' => 'Colombo',
        'city' => 'Maharagama',
        'workspace' => 'call-center',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9013,
        'orderNumber' => 'FO-GL-88101',
        'customerName' => 'Priyantha Silva',
        'customerPhone' => '0719988776',
        'secondaryPhone' => '',
        'address' => '5 Lotus Road, Colombo',
        'itemCount' => 1,
        'itemCode' => '1842',
        'itemName' => 'Vitamin C Serum / 30ml',
        'amount' => 4600,
        'subtotal' => 4200,
        'discount' => 0,
        'courierFee' => 400,
        'currency' => 'LKR',
        'assignment' => 'assigned',
        'ccaId' => 'cca-1',
        'ccaName' => 'Nimali Perera',
        'supplierId' => 'supplier-1',
        'supplierName' => 'Lanka Beauty Supply',
        'status' => 'pending',
        'statusLabel' => 'Pending',
        'source' => 'manual',
        'createdAt' => '2026-09-13T06:40:00+05:30',
        'courierName' => null,
        'district' => 'Colombo',
        'city' => 'Colombo',
        'workspace' => 'call-center',
        'isGlobal' => true,
        'resellerName' => 'Ocean Cart LK',
        'isEditable' => false,
    ],
    [
        'id' => 9014,
        'orderNumber' => 'FO-GL-88122',
        'customerName' => 'Fathima Rizwan',
        'customerPhone' => '0765544332',
        'secondaryPhone' => '0112233445',
        'address' => '22 Galle Face, Colombo',
        'itemCount' => 2,
        'itemCode' => '1760',
        'itemName' => 'Collagen Cream / 50ml',
        'amount' => 7200,
        'subtotal' => 6800,
        'discount' => 200,
        'courierFee' => 600,
        'currency' => 'LKR',
        'assignment' => 'pool',
        'ccaId' => null,
        'ccaName' => null,
        'supplierId' => 'supplier-3',
        'supplierName' => 'Ceylon Care Depot',
        'status' => '2nd-attempt',
        'statusLabel' => '2nd Attempt',
        'source' => 'meta',
        'createdAt' => '2026-09-11T12:15:00+05:30',
        'courierName' => null,
        'district' => 'Colombo',
        'city' => 'Colombo',
        'workspace' => 'call-center',
        'isGlobal' => true,
        'resellerName' => 'Island Retail Hub',
        'isEditable' => false,
    ],
    [
        'id' => 9009,
        'orderNumber' => 'FO-23990',
        'customerName' => 'Nadeesha Rathnayake',
        'customerPhone' => '0763344556',
        'secondaryPhone' => '0117788990',
        'address' => '54 Main Street, Colombo',
        'itemCount' => 1,
        'itemCode' => '2014',
        'itemName' => 'Face Wash / 150ml',
        'amount' => 1950,
        'subtotal' => 1600,
        'discount' => 0,
        'courierFee' => 350,
        'currency' => 'LKR',
        'assignment' => 'assigned',
        'ccaId' => 'cca-2',
        'ccaName' => 'Kasun Jayawardena',
        'supplierId' => 'supplier-1',
        'supplierName' => 'Lanka Beauty Supply',
        'status' => 'returned',
        'statusLabel' => 'Returned',
        'source' => 'manual',
        'createdAt' => '2026-08-28T13:20:00+05:30',
        'courierName' => 'Pronto Lanka',
        'district' => 'Colombo',
        'city' => 'Colombo',
        'workspace' => 'archived',
        'archive' => 'returned',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
    [
        'id' => 9010,
        'orderNumber' => 'FO-23970',
        'customerName' => 'Chamara Dissanayake',
        'customerPhone' => '0712233445',
        'secondaryPhone' => '',
        'address' => '2 School Lane, Negombo',
        'itemCount' => 1,
        'itemCode' => '1888',
        'itemName' => 'Sunscreen / 50ml',
        'amount' => 3300,
        'subtotal' => 2900,
        'discount' => 0,
        'courierFee' => 400,
        'currency' => 'LKR',
        'assignment' => 'unassigned',
        'ccaId' => null,
        'ccaName' => null,
        'supplierId' => 'supplier-2',
        'supplierName' => 'Island Wellness',
        'status' => 'expired',
        'statusLabel' => 'Expired',
        'source' => 'meta',
        'createdAt' => '2026-08-20T08:45:00+05:30',
        'courierName' => null,
        'district' => 'Gampaha',
        'city' => 'Negombo',
        'workspace' => 'archived',
        'archive' => 'expired',
        'isGlobal' => false,
        'resellerName' => 'Feeder Demo',
        'isEditable' => true,
    ],
];

$orderUiMockSample = $orderUiMockOrders[0];
foreach ($orderUiMockOrders as $mockOrder) {
    if (($orderUiScreen ?? '') === 'hold' && $mockOrder['status'] === 'hold') {
        $orderUiMockSample = $mockOrder;
        break;
    }
    if (($orderUiScreen ?? '') === 'expiring' && $mockOrder['status'] === 'expiring') {
        $orderUiMockSample = $mockOrder;
        break;
    }
    if (($orderUiScreen ?? '') === 'expired' && $mockOrder['status'] === 'expired') {
        $orderUiMockSample = $mockOrder;
        break;
    }
    if (in_array($orderUiScreen ?? '', ['confirm', 'view', 'edit'], true) && $mockOrder['status'] === 'pending') {
        $orderUiMockSample = $mockOrder;
        break;
    }
}

return [
    'orderUiMockCcas' => [
        ['id' => 'cca-1', 'name' => 'Nimali Perera'],
        ['id' => 'cca-2', 'name' => 'Kasun Jayawardena'],
        ['id' => 'cca-3', 'name' => 'Ishara Fernando'],
    ],
    'orderUiMockSuppliers' => [
        ['id' => 'supplier-1', 'name' => 'Lanka Beauty Supply'],
        ['id' => 'supplier-2', 'name' => 'Island Wellness'],
        ['id' => 'supplier-3', 'name' => 'Ceylon Care Depot'],
    ],
    'orderUiMockProducts' => [
        ['code' => '1842', 'name' => 'Vitamin C Serum / 30ml'],
        ['code' => '1901', 'name' => 'Hair Oil / 100ml'],
        ['code' => '1760', 'name' => 'Collagen Cream / 50ml'],
        ['code' => '2014', 'name' => 'Face Wash / 150ml'],
        ['code' => '1888', 'name' => 'Sunscreen / 50ml'],
    ],
    'orderUiMockCouriers' => [
        [
            'id' => 'courier-1',
            'name' => 'Pronto Lanka',
            'districts' => [
                ['name' => 'Colombo', 'cities' => ['Colombo', 'Dehiwala', 'Nugegoda']],
                ['name' => 'Gampaha', 'cities' => ['Negombo', 'Gampaha', 'Ja-Ela']],
            ],
        ],
        [
            'id' => 'courier-2',
            'name' => 'Island Express',
            'districts' => [
                ['name' => 'Kandy', 'cities' => ['Kandy', 'Peradeniya']],
                ['name' => 'Colombo', 'cities' => ['Colombo', 'Maharagama']],
            ],
        ],
    ],
    'orderUiMockOrders' => $orderUiMockOrders,
    'orderUiMockHistory' => [
        ['order_number' => 'FO-22110', 'date' => '12 Aug 2026', 'reseller_company' => 'Feeder Demo', 'reseller_name' => 'Nimali Perera', 'items' => 'Vitamin C Serum / 30ml', 'amount' => 4850, 'currency' => 'LKR', 'courier_name' => 'Pronto Lanka', 'tracking_number' => 'PL88211', 'status' => 'Delivered'],
        ['order_number' => 'FO-21804', 'date' => '02 Jul 2026', 'reseller_company' => 'Feeder Demo', 'reseller_name' => 'Kasun Jayawardena', 'items' => 'Hair Oil / 100ml', 'amount' => 3200, 'currency' => 'LKR', 'courier_name' => 'Island Express', 'tracking_number' => 'IE44109', 'status' => 'Returned'],
        ['order_number' => 'FO-21440', 'date' => '18 May 2026', 'reseller_company' => 'Feeder Demo', 'reseller_name' => 'Ishara Fernando', 'items' => 'Face Wash / 150ml', 'amount' => 2100, 'currency' => 'LKR', 'courier_name' => 'Pronto Lanka', 'tracking_number' => 'PL77012', 'status' => 'Cancelled'],
    ],
    'orderUiMockTimeline' => [
        ['type' => 'created', 'title' => 'Order created', 'description' => 'Manual order entry by reseller', 'user' => 'You', 'at' => 'Today · 8:15 AM'],
        ['type' => 'customer', 'title' => 'Customer identified', 'description' => 'Sanduni Wijesinghe matched by phone number', 'user' => 'System', 'at' => 'Today · 8:16 AM'],
        ['type' => 'product', 'title' => 'Product added', 'description' => 'Vitamin C Serum / 30ml × 2', 'user' => 'You', 'at' => 'Today · 8:17 AM'],
        ['type' => 'courier', 'title' => 'Courier selected', 'description' => 'Pronto Lanka · Gampaha · Negombo', 'user' => 'You', 'at' => 'Today · 8:18 AM'],
        ['type' => 'market', 'title' => 'Note added', 'description' => 'Customer prefers evening delivery.', 'user' => 'Nimali Perera', 'at' => 'Today · 9:02 AM'],
    ],
    'orderUiMockImportRows' => [
        ['row' => 2, 'name' => 'Sanduni Wijesinghe', 'tp_1' => '0771234567', 'tp_2' => '0112345678', 'address' => 'No. 12, Temple Road, Negombo', 'price' => '4500.00', 'qty' => 2, 'item_code' => '1842', 'delivery' => '500.00', 'state' => 'valid', 'stateLabel' => 'Valid'],
        ['row' => 3, 'name' => 'Ruwan Silva', 'tp_1' => '0769876543', 'tp_2' => '', 'address' => '45 Galle Road, Dehiwala', 'price' => '2800.00', 'qty' => 1, 'item_code' => '1901', 'delivery' => '400.00', 'state' => 'created', 'stateLabel' => 'Created'],
        ['row' => 4, 'name' => 'Banned Customer', 'tp_1' => '0770000001', 'tp_2' => '0770000002', 'address' => 'Unknown', 'price' => '1500.00', 'qty' => 1, 'item_code' => '2014', 'delivery' => '350.00', 'state' => 'banned', 'stateLabel' => 'Banned'],
        ['row' => 5, 'name' => '', 'tp_1' => 'abc', 'tp_2' => '', 'address' => '', 'price' => '', 'qty' => 0, 'item_code' => '', 'delivery' => '', 'state' => 'invalid', 'stateLabel' => 'Invalid'],
    ],
    'orderUiMockSample' => $orderUiMockSample,
];
