@php
    $mode = $mode ?? 'create';
    $isEdit = $mode === 'edit';
    $agent = $agent ?? null;
    $assignedPermissions = $assignedPermissions ?? [];
    $firstName = $agent['first_name'] ?? '';
    $lastName = $agent['last_name'] ?? '';
    $phone = $agent['phone'] ?? '';
    $username = $agent['username'] ?? '';
    $commission = $agent['commission'] ?? 100;
    $status = $agent['status'] ?? 'active';
@endphp

<div class="row g-4">
    <div class="col-lg-8">
        <div class="card bg-white border border-white rounded-10 p-20 mb-4">
            <h3 class="mb-2">Personal information</h3>
            <p class="fs-14 text-body mb-20">These details identify the call center agent on the reseller portal.</p>
            <div class="row g-3">
                <div class="col-md-6">
                    <label for="agentFirstName" class="label fs-16 mb-2">First Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="agentFirstName" name="first_name"
                        value="{{ $firstName }}" placeholder="Enter first name" autocomplete="given-name"
                        data-username-source="first">
                </div>
                <div class="col-md-6">
                    <label for="agentLastName" class="label fs-16 mb-2">Last Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="agentLastName" name="last_name"
                        value="{{ $lastName }}" placeholder="Enter last name" autocomplete="family-name"
                        data-username-source="last">
                </div>
                <div class="col-12">
                    <label for="agentPhone" class="label fs-16 mb-2">Phone Number <span class="text-danger">*</span></label>
                    <input type="text" class="form-control" id="agentPhone" name="phone"
                        value="{{ $phone }}" placeholder="077 123 4567" inputmode="tel" autocomplete="tel">
                    <div class="form-text">Use the agent’s Sri Lankan mobile number, for example 077 123 4567.</div>
                </div>
            </div>
        </div>

        <div class="card bg-white border border-white rounded-10 p-20 mb-4">
            <h3 class="mb-2">Login</h3>
            @if ($isEdit)
                <p class="fs-14 text-body mb-20">The username is generated by the system and is not normally changed.</p>
                <label for="agentUsername" class="label fs-16 mb-2">Username</label>
                <div class="input-group">
                    <input type="text" class="form-control bg-light" id="agentUsername" name="username"
                        value="{{ $username }}" readonly tabindex="-1" aria-readonly="true">
                    <span class="input-group-text bg-light text-body">System generated</span>
                </div>
                <div class="form-text">This username was assigned when the agent was created and cannot be edited here.</div>
            @else
                <p class="fs-14 text-body mb-20">
                    Usernames are generated automatically when the agent is created. Do not enter a username manually.
                </p>
                <label for="agentUsernamePreview" class="label fs-16 mb-2">Username</label>
                <div class="input-group">
                    <input type="text" class="form-control bg-light" id="agentUsernamePreview" name="username_preview"
                        value="" placeholder="Will be generated automatically" readonly tabindex="-1"
                        aria-readonly="true" data-username-preview>
                    <span class="input-group-text bg-light text-body">Auto-generated</span>
                </div>
                <div class="form-text">
                    Preview format: <span class="text-secondary">cca.firstname.lastname</span>.
                    The final username is assigned by the system after the agent is created.
                </div>
            @endif
        </div>

        @unless ($isEdit)
            <div class="card bg-white border border-white rounded-10 p-20 mb-4" id="password-show-hide">
                <h3 class="mb-2">Password</h3>
                <p class="fs-14 text-body mb-20">Set the initial password the agent will use to sign in to the reseller portal.</p>
                <div class="row g-3">
                    <div class="col-md-6">
                        <label for="agentPassword" class="label fs-16 mb-2">Password <span class="text-danger">*</span></label>
                        <div class="password-wrapper position-relative password-container">
                            <input type="password" class="form-control text-secondary password" id="agentPassword"
                                name="password" placeholder="Enter password" autocomplete="new-password"
                                data-password-input>
                            <i class="ri-eye-off-line password-toggle-icon translate-middle-y top-50 position-absolute cursor text-secondary"
                                style="color: #A9A9C8; font-size: 22px; right: 15px;" data-password-toggle
                                role="button" tabindex="0" aria-label="Show password"></i>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <label for="agentPasswordConfirmation" class="label fs-16 mb-2">Confirm Password <span class="text-danger">*</span></label>
                        <div class="password-wrapper position-relative password-container">
                            <input type="password" class="form-control text-secondary password" id="agentPasswordConfirmation"
                                name="password_confirmation" placeholder="Confirm password" autocomplete="new-password"
                                data-password-input>
                            <i class="ri-eye-off-line password-toggle-icon translate-middle-y top-50 position-absolute cursor text-secondary"
                                style="color: #A9A9C8; font-size: 22px; right: 15px;" data-password-toggle
                                role="button" tabindex="0" aria-label="Show confirm password"></i>
                        </div>
                    </div>
                </div>
            </div>
        @endunless

        <div class="card bg-white border border-white rounded-10 p-20 mb-4">
            <div class="d-flex align-items-start justify-content-between flex-wrap gap-2 mb-2">
                <div>
                    <h3 class="mb-2">Permissions</h3>
                    <p class="fs-14 text-body mb-0">
                        Choose what this call center agent can do. These checkboxes are a visual preview and are not connected to the permission engine yet.
                    </p>
                </div>
            </div>
            <div class="mt-3">
                @include('pages.call-center.agents.partials.permission-fields', [
                    'permissionCatalog' => $permissionCatalog,
                    'assignedPermissions' => $assignedPermissions,
                ])
            </div>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card bg-white border border-white rounded-10 p-20 mb-4">
            <h3 class="mb-2">Commission</h3>
            <p class="fs-14 text-body mb-20">
                This is the agent’s commission for each successfully completed order. It is not calculated from earnings on this screen.
            </p>
            <label for="agentCommission" class="label fs-16 mb-2">Commission per completed order <span class="text-danger">*</span></label>
            <div class="input-group">
                <span class="input-group-text">LKR</span>
                <input type="text" class="form-control" id="agentCommission" name="commission"
                    value="{{ number_format((float) $commission, 2, '.', '') }}"
                    inputmode="decimal" placeholder="100.00">
            </div>
            <div class="form-text">Example: LKR 100.00 paid when an order is successfully completed.</div>
        </div>

        <div class="card bg-white border border-white rounded-10 p-20 mb-4">
            <h3 class="mb-2">Account status</h3>
            <p class="fs-14 text-body mb-20">Inactive agents remain in the list but cannot be used for new call center work.</p>
            <div class="d-flex flex-column gap-2">
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="status" id="agentStatusActive"
                        value="active" @checked($status === 'active')>
                    <label class="form-check-label" for="agentStatusActive">
                        <span class="d-block fw-medium">Active</span>
                        <span class="fs-13 text-body">Agent can sign in and handle assigned work.</span>
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" name="status" id="agentStatusInactive"
                        value="inactive" @checked($status === 'inactive')>
                    <label class="form-check-label" for="agentStatusInactive">
                        <span class="d-block fw-medium">Inactive</span>
                        <span class="fs-13 text-body">Agent is retained but blocked from new activity.</span>
                    </label>
                </div>
            </div>
        </div>

        @if ($isEdit)
            <div class="card bg-white border border-white rounded-10 p-20 mb-4">
                <h3 class="mb-2">Password</h3>
                <p class="fs-14 text-body mb-20">
                    Change the agent’s sign-in password without altering other account details.
                </p>
                <button type="button" class="btn btn-outline-secondary w-100" data-bs-toggle="modal"
                    data-bs-target="#changePasswordModal">
                    Change Password
                </button>
            </div>
        @endif

        <div class="card bg-white border border-white rounded-10 p-20 mb-4">
            <div class="d-flex flex-wrap gap-2">
                @if ($isEdit)
                    <button type="submit" class="btn btn-primary text-white">Save Changes</button>
                    <a href="{{ route('ui.call-center.agents.show', $agent['slug']) }}" class="btn btn-outline-secondary">Cancel</a>
                @else
                    <button type="submit" class="btn btn-primary text-white">Create Agent</button>
                    <a href="{{ route('ui.call-center.agents.index') }}" class="btn btn-outline-secondary">Cancel</a>
                @endif
            </div>
        </div>
    </div>
</div>
